* Hungarian Goulash
** Ingredients
- 1 Medium Onion, diced
- 2+ Tbs Hungarian Sweet Paprika
- 1/2 Tsp Caraway Seed
- 2 Bay Leaves
- 1.5 lbs Beef Stew Meat
- 16 oz Beef Stock
- 5 Red Potatoes, peeled and cubed
- Pinch of Salt(to taste)
** Preperation
   1. Brown the stew meat in a large pot or dutch oven.  Remove the meat when browned.
   2. Saute the diced onion until it turns translucent.  Some more oil or butter may be needed.
   3. Add paprika and beef stock and stir.
   4. Add the bay leaves, stew meat, and caraway seed.  The meat should be submersed in liquid, add more if necessary.
   5. Simmer covered for 2 hours.  Beef should be tender at this time, check and adjust cooking time as necessary.
   6. Add potatoes.  Adjust the liquid with water or stock to cover the potatoes.  Cook for 15-25 minutes.
   7. When potatoes are soft, the goulash is done.  Add paprika and salt to taste.
**** This recipe based on http://www.culinaryartsblog.com/index.php/2006/02/07/simple_hungarian_goulash_gulyasleves_rec
