* Neopolitan-Style Pizza Crust
** Ingredients
- 4.5 cups Unbleached All Purpose Flour or Bread Flour
- 1.75 teaspoons salt
- 1 teaspoon yeast
- .25 cup olive oil
- 1.75 cups ice cold water
- Semolina flour or cornmeal for dusting peel
** Preperation Day
   1. Stir dry ingredients together.
   2. Mix water and oil in slowly with a metal spoon.  Have a bowl of water to dip the spoon into if necessary.
   3. Mix dough(with hand) having bowl of water ready if your hand/spoon gets too sticky for 5-7 minutes until the dough is sticky, but not stuck to the sides of the bowl.
   4. Seperate dough into six six ounce balls.  Dust with flour and spray with oil.  Place covered in refridgerator overnight.  Dough can then be kept three days in refridgerator or three months in freezer.
** Pizza Day
   1. Two hours before dust a clean counter with flour or do it on the peel and remove the desired number of dough balls.
   2. Dust hands and dough with a bit of flour.
   3. Flatten balls into ~5 inch disks.
   4. Cover lightly with food wrap or towel and rest for 2 hours.
   5. 45 minutes to baking time heat up the oven as hot as it will go.  A stone is recommended.
   6. Dust your hands and shape the dough to about a 9-12 inch diameter.  Different techniques result in different pizzas.
   7. Lay it on the dusted peel(I like cornmeal).
   8. Top the crust with the idea that less is more.
   9. Pizza is done in ~5-8 minutes
** Different Techniques on Stretching Crust
*** Knuckle turning
**** This method seems to give a bit too large of an outer crust.  However it does come out delicious, sort of reminds me of CPK.
*** Finger stretching on counter
**** Stretching the crust to the max can achieve a more cracker like crust.
*** Rolling Pin
**** This method is somewhere in between cracker crust and too big of an outer rim.  The crust is more dense, but not crisp.  Sort of like Kashi pizza crust.
